[WIP] Boolean cast
screwdriver-cd/screwdriver pull request #2242
Opened 2020-10-10 00:56 UTC by sakka2

## Context

## Objective

## References

## License
I confirm that this contribution is made under a BSD license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2020-10-12 04:27 UTC, kkokufud commented
[imo] Do we need to think about allowing the uppercase value?
ex. `True` `TRUE`

2020-10-12 06:50 UTC, kkokufud approved these changes
LGTM

2020-10-12 17:44 UTC, tkyi approved these changes

2020-10-12 23:40 UTC, DekusDenial commented
you can instead do something similar to https://github.com/screwdriver-cd/screwdriver/pull/2245/files#diff-f08ec2742d167ad6f3ad6485baab2bbbe1271d3e9eb7cf7e7792ba1c7e012171R405-R407

2020-10-13 00:44 UTC, jithine requested changes
We should leverage native `config` package capabilities by using it's boolean parser. https://github.com/lorenwest/node-config/commit/97d4a5d251e69aeb3b6931af318a4a6a71360d7e#diff-774a94f3cb4758afd1f7feef2c1baa0a9a49ec1804a6a54c1264a607e30d7b27R7-R13

2020-10-13 01:38 UTC, sugarnaoming commented
> We should leverage native `config` package capabilities by using it's boolean parser. [lorenwest/node-config@97d4a5d#diff-774a94f3cb4758afd1f7feef2c1baa0a9a49ec1804a6a54c1264a607e30d7b27R7-R13](https://github.com/lorenwest/node-config/commit/97d4a5d251e69aeb3b6931af318a4a6a71360d7e#diff-774a94f3cb4758afd1f7feef2c1baa0a9a49ec1804a6a54c1264a607e30d7b27R7-R13)

Thank you.
Fixed use node-config parser, and revert to commits that were no longer needed.

2020-10-13 01:44 UTC, DekusDenial commented
I had to remove my previous comment because you would need to upgrade node-config to the version that includes boolean parser otherwise `__format: boolean` has no effect. Or, you can sidestep this by using `__format: json` so it can parse it as boolean.

2020-10-13 02:26 UTC, sugarnaoming commented
> I had to remove my previous comment because you would need to upgrade node-config to the version that includes boolean parser otherwise `__format: boolean` has no effect. But newer node-config is immutable and you would need to make some other changes as well. Or, you can sidestep this by using `__format: json` so it can parse string `true/false` as boolean.

Thank you.
In version 1.31.0, only the conversion to boolean was successful, so I was mistaken.  (In version 1.31.0, everything was converted to false.
This time we'll use the json format.

2020-10-13 08:39 UTC, sugarnaoming commented
Thank you for comment.
This time is fixed to use convert function.
There are two reasons for this
- Not enough version to use boolean config parser.
  - If we want to increase the version of config, we need to verify that there is no problem with the upgraded major version.
- If "__format: json" is specified, any value other than true/false (e.g. True/False) will result in an error.
  - yaml determines that `yes`, `y`, etc. are also true. (ref: https://yaml.org/type/bool.html)

2020-10-14 08:35 UTC, kkokufud approved these changes

2020-10-15 14:52 UTC, jithine approved these changes

2020-10-15 17:22 UTC, adong commented on bin/server
> +    // trueList refers to https://yaml.org/type/bool.html
👍

2020-10-16 08:29 UTC, sugarnaoming commented
We created an issue to raise the version of node-config.
We may be able to work on it ourselves if we have the time.
https://github.com/screwdriver-cd/screwdriver/issues/2253

2020-10-19 05:42 UTC, merged