feat(2767): Add stage api
screwdriver-cd/screwdriver pull request #2951
Opened 2023-11-10 00:06 UTC by tkyi

## Context

Split up the API PR into API and workflow.

## Objective

This PR adds stage API endpoints.

## References

Related to https://github.com/screwdriver-cd/screwdriver/issues/2767

## License
I confirm that this contribution is made under a BSD license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2023-11-14 16:23 UTC, sagar1312 requested changes

2023-11-14 16:23 UTC, sagar1312 commented on plugins/pipelines/README.md
> +Will get latest commit event's stages if no event ID is provided
With the latest schema changes, `stages` are no longer associated to `event`. I believe `GET /pipelines/{id}/stages?eventId={eventId}` is no longer valid endpoint.
```suggestion
```

2023-11-16 16:27 UTC, sagar1312 requested changes
Also remove `GET /stages/{id}/stageBuilds?eventId={eventId}` from `plugins/stages/README.md`

Not entirely related to this PR. It will nice to have some test to validate all the referenced factories exists.
Ex: New factory `stageBuildFactory` is being referenced which is not yet available in the latest `models` dependency.

2023-11-16 23:57 UTC, tkyi commented on test/plugins/events.test.js
> +            stageBuilds = getStageBuildMocks(testStageBuilds);
removed from models

2023-11-16 23:58 UTC, tkyi commented on plugins/helper.js
> +function getFullStageJobName({ stageName, jobName }) {
removed

2023-11-17 16:20 UTC, sagar1312 reviewed
Looks good. I believe, this PR should be merged after https://github.com/screwdriver-cd/models/pull/570 goes in.

Note: It will be nice to explicitly upgrade to the `screwdriver-models` version required in the `package.json` once it is available.

2023-11-20 15:04 UTC, sagar1312 approved these changes

2023-11-20 15:04 UTC, merged